### ISSUE TITLE
didResolveDeepLink doesn't seem to do anything

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-swift-appsflyer#10]
Looking over the code for `AppsFlyerDestination::didResolveDeepLink`, aside from the optional delegate, none of the rest of the code gets called, ever.

At the top of the routine, you see this:
```
        switch result.status {
        case .notFound:
            return
        case .failure:
            return
        case .found:
            return
        }
```

They all return. None of the code following this will ever get called. 😕

**Comment by alanjcharles** [comment]
Thanks again @skydivedan. Fixed in `1.1.5`
