### ISSUE TITLE
Debug mode is enabled per default

### ISSUE THREAD

**Issue by mickyzinho** [segment-integrations/analytics-swift-appsflyer#4]
In the `AppsFlyerDestination`, the debug mode for the apps flyer lib is set to true: `AppsFlyerLib.shared().isDebug = true` and there is no way to change this. Console logs `[AppsFlyerSDK] [com.apple.main-thread] * AppsFlyer is set to debug mode. This should only be used in development environment! *` 
We worked around this by setting `AppsFlyerLib.shared().isDebug = false` after the Segment setup, but this does not always seem to take effect (maybe there's a race condition).
Please make this false by default and/or provide a way to override the value in the destination.

**Comment by bsneed** [comment]
cc @alanjcharles

**Comment by alanjcharles** [comment]
resolved in `1.1.5`
