### ISSUE TITLE
any intent to support segDelegate & segDLDelegate that can message back to the app?

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-swift-appsflyer#8]
In the old [Segment AppsFlyer integration](https://github.com/AppsFlyerSDK/segment-appsflyer-ios), there were values that could be passed into the integration. `segDelegate` would get called for conversion and attribution. And `segDLDelegate` was there for `didResolveDeepLink`.

In this plugin, the plugin _is the delegate_, and there is no way to communicate back out to whomever instantiated this plugin.

It seems that if you did this, you could remove the code that says 
> "Uncomment the following code and alter to fit your implementation..."

and then just call the delegates, and have the owning app handle it.

Is there any intent to add this back in?

**Comment by alanjcharles** [comment]
just merged your PR, thanks again!
